"""empty message

Revision ID: fc589c55e1d5
Revises: 64aef7fa6402
Create Date: 2023-12-04 08:29:38.181688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc589c55e1d5'
down_revision = '64aef7fa6402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id_report', sa.Integer(), nullable=False),
    sa.Column('path_file', sa.String(length=255), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('title_report', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_report')
    )
    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.alter_column('nip',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('nip',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    op.drop_table('report')
    # ### end Alembic commands ###
